varsion: 2
jobs:
    build:
        docker:
           - image: circleci/python:3.8.2

        working_directory: ~/repo

        steps:
            - checkout
            - run:
                name: Setup VirtualEnv
                command: |
                    python -m venv venv
                    venv\Scripts\activate.bin
                    pip install -r requirements.txt
            - run:
                name: Run Tests
                command: |
                    venv\Scripts\activate.bin
                    flake8 --statistics
                    pytest -v --cov
