varsion: 2
jobs:
    build:
        docker:
           - image: circleci/python:3.8.2
             auth:
                username: usernameDockerHub
                password: passwordDockerHub 
        working_directory: ~/repo

        steps:
            - checkout
            - run:
                name: Setup VirtualEnv
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - run:
                name: Run Tests
                command: |
                    . venv/bin/activate
                    flake8 --exclude=venv* --statistics
                    pytest -v --cov=calculator
          #   - setup_remote_docker:
           #     docker_layer_caching: true
            #- run:
             #   name: Build and push Docker image
              #  command: |
               #     . venv/bin/activate
                #    pyinstaller -F calculator.py
                 #   docker build -t $UsernameDockerHub/falka164/calc-repo:ver1 .
                  #  echo $passwordDockerHub | docker login -u $UsernameDockerHub --password-stdin
                   # docker push falka164/calc-repo:ver1