varsion: 2
jobs:
    build:
        docker:
           - image: circleci/python:3.8

        working_directory: ~/repo

        steps:
            - checkout
            - run:
                name: Setup VirtualEnv
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - run:
                name: Run Tests
                command: |
                    . venv/bin/activate
                    flake8 --exclude=venv* --statistics
                    pytest -v --cov=calculator
